<%@ Page Title="" Language="C#" MasterPageFile="~/Master Pages/DefaultLayoutNoSidebar.master" AutoEventWireup="true" CodeBehind="Feedback.aspx.cs" Inherits="EducationOverflow.Content.MemberPages.Feedback" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head_content" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="status_bar_content" runat="server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="main_content_body_content" runat="server">
    <asp:GridView ID="UserFeedbackGridView" runat="server" AllowPaging="True" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="UserQuestionFeedbackDataSource"
        Height="100%" Width="100%">
        <Columns>
            
        </Columns>
    </asp:GridView>

    <asp:ObjectDataSource ID="UserQuestionFeedbackDataSource" runat="server" DeleteMethod="DeleteUserQuestionFeedback" 
        SelectMethod="SelectUserQuestionFeedback" TypeName="Business.UserQuestionFeedback">
        <DeleteParameters>
            <asp:Parameter Name="questionId" Type="Int64" />
            <asp:Parameter Name="userId" Type="Int64" />
        </DeleteParameters>
        <SelectParameters>
            <asp:Parameter Name="userId" Type="Int64" />
        </SelectParameters>
    </asp:ObjectDataSource>
</asp:Content>
