<%@ Page Title="" Language="C#" MasterPageFile="~/Master Pages/DefaultLayoutNoSidebar.master" AutoEventWireup="true" CodeBehind="ReportedQuestions.aspx.cs" Inherits="EducationOverflow.Content.Member_Pages.ReportQuestion" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head_content" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="status_bar_content" runat="server">
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="main_content_body_content" runat="server">
    <h1>
        My Reported Questions
    </h1>
    <asp:GridView ID="ReportedQuestionsGridView" runat="server" AllowPaging="True" AutoGenerateColumns="False" 
        DataSourceID="ReportedQuestionsDataSource" Height="100%" Width="100%" AutoGenerateDeleteButton="True" 
        DataKeyNames="Id">
        <Columns>
            <asp:BoundField DataField="SiteName" HeaderText="Site Name" SortExpression="SiteName" />
            <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
            <asp:BoundField DataField="OptionalDescription" HeaderText="Reason" SortExpression="OptionalDescription" />
            <asp:BoundField DataField="PredefinedDescription" HeaderText="Description" SortExpression="PredefinedDescription" />
        </Columns>
        <EmptyDataTemplate>
            You have not reported any questions.
        </EmptyDataTemplate>
    </asp:GridView>
    
    <asp:ObjectDataSource ID="ReportedQuestionsDataSource" runat="server" DeleteMethod="DeleteReportedQuestionFromUserView" OldValuesParameterFormatString="question{0}" SelectMethod="SelectQuestionsFromUserView" TypeName="Business.UserReportedQuestions">
        <DeleteParameters>
            <asp:Parameter Name="userId" Type="Int64" />
        </DeleteParameters>
        <SelectParameters>
            <asp:Parameter Name="userId" Type="Int64" />
        </SelectParameters>
    </asp:ObjectDataSource>
</asp:Content>

