<%@ Page Title="" Language="C#" MasterPageFile="~/Master Pages/DefaultLayoutNoSidebar.master" AutoEventWireup="true" CodeBehind="ReportedQuestionDetails.aspx.cs" Inherits="EducationOverflow.Content.AdminPages.ReportedQuestionDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head_content" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="status_bar_content" runat="server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="main_content_body_content" runat="server">
    <h1>
        Reported Question Details
    </h1>
    <asp:DetailsView ID="ReportedQuestionDetailsView" runat="server" AutoGenerateRows="False" DataSourceID="ReportedQuestionDetailsDataSource" 
        AutoGenerateDeleteButton="True" FieldHeaderStyle-Width="175px" FieldHeaderStyle-HorizontalAlign="Center" Height="100%" Width="100%">
        <Fields>
            <asp:BoundField DataField="Id" HeaderText="Question Id" SortExpression="Id" />
            <asp:BoundField DataField="Name" HeaderText="Site Name" SortExpression="Name" />
            <asp:BoundField DataField="URL" HeaderText="URL" SortExpression="URL" />
            <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
            <asp:BoundField DataField="UpVotes" HeaderText="Up Votes" SortExpression="UpVotes" />
            <asp:BoundField DataField="DownVotes" HeaderText="Down Votes" SortExpression="DownVotes" />
            <asp:BoundField DataField="Body" HeaderText="Body" SortExpression="Body" HtmlEncode="false" />
            <asp:BoundField DataField="UserId" HeaderText="User Id" SortExpression="UserId" />
            <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:BoundField DataField="OptionalDescription" HeaderText="Optional Description" SortExpression="OptionalDescription" />
        </Fields>
        <EmptyDataTemplate>
            The specified question report does not exist (see query string parameters in url).
        </EmptyDataTemplate>
    </asp:DetailsView>
    <asp:ObjectDataSource ID="ReportedQuestionDetailsDataSource" runat="server" OldValuesParameterFormatString="original_{0}" SelectMethod="SelectReportedQuestionDetails" DeleteMethod="DeleteQuestionReport" TypeName="Business.ReportedQuestionDetails">
        <SelectParameters>
            <asp:QueryStringParameter Name="userId" QueryStringField="UserId" Type="Int64" />
            <asp:QueryStringParameter Name="questionId" QueryStringField="QuestionId" Type="Int64" />
        </SelectParameters>
        <DeleteParameters>
            <asp:QueryStringParameter Name="userId" QueryStringField="UserId" Type="Int64" />
            <asp:QueryStringParameter Name="questionId" QueryStringField="QuestionId" Type="Int64" />
        </DeleteParameters>
    </asp:ObjectDataSource>
</asp:Content>
